<?xml version="1.0"?>
<!--
** DO NOT EDIT THIS FILE.
** If you make changes to this file while any VirtualBox related application
** is running, your changes will be overwritten later, without taking effect.
** Use VBoxManage or the VirtualBox Manager GUI to make changes.
**
** Written by VirtualBox 7.2.8 (r173730)
-->
<VirtualBox xmlns="http://www.virtualbox.org/" version="1.19-windows">
  <Machine uuid="{${ machine_guid }}" name="${ name }" OSType="${ os_type }" snapshotFolder="Snapshots" lastStateChange="2026-05-24T18:35:15Z">
    <MediaRegistry>
      <HardDisks>
${ disks }
      </HardDisks>
      <DVDImages>
${ isos }
      </DVDImages>
    </MediaRegistry>
    <Hardware>
      <Memory RAMSize="${ memory }"/>
      <Boot>
        <Order position="1" device="HardDisk"/>
        <Order position="2" device="DVD"/>
        <Order position="3" device="None"/>
        <Order position="4" device="None"/>
      </Boot>
      <Display controller="VMSVGA" VRAMSize="16"/>
      <Firmware${ uefi }/>
      <BIOS>
        <IOAPIC enabled="true"/>
        <SmbiosUuidLittleEndian enabled="true"/>
        <AutoSerialNumGen enabled="true"/>
      </BIOS>
      <USB>
        <Controllers>
          <Controller name="OHCI" type="OHCI"/>
          <Controller name="EHCI" type="EHCI"/>
        </Controllers>
      </USB>
      <Network>
${ nics }
      </Network>
      <AudioAdapter codec="AD1980" useDefault="true" driver="WAS" enabled="true" enabledOut="true"/>
      <Clipboard/>
      <StorageControllers>
        <StorageController name="IDE" type="PIIX4" PortCount="${ iso_ports }" useHostIOCache="true" Bootable="true">
${ ide_attach }
        </StorageController>
		<StorageController name="${ controller_name }" type="${ controller_type }" PortCount="${ controller_ports }" useHostIOCache="false" Bootable="true" ${ controller_flags }>
${ disk_attach }
        </StorageController>
      </StorageControllers>
      <RTC localOrUTC="UTC"/>
      <CPU count="${ cpu }">
        <HardwareVirtExLargePages enabled="true"/>
        <PAE enabled="true"/>
        <LongMode enabled="true"/>
        <X2APIC enabled="true"/>
      </CPU>
    </Hardware>
  </Machine>
</VirtualBox>
